// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieForum.Data;

namespace MovieForum.Data.Migrations
{
    [DbContext(typeof(MovieForumContext))]
    [Migration("20221104200254_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieForum.Data.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Tom",
                            IsDeleted = false,
                            LastName = "Cruize"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Tom",
                            IsDeleted = false,
                            LastName = "Holand"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Paul",
                            IsDeleted = false,
                            LastName = "Walker"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Florence",
                            IsDeleted = false,
                            LastName = "Pugh"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Ethan",
                            IsDeleted = false,
                            LastName = "Hawke"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Danielle",
                            IsDeleted = false,
                            LastName = "Panabaker"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Ryan",
                            IsDeleted = false,
                            LastName = "Reynolds"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Taylor",
                            IsDeleted = false,
                            LastName = "Russel"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Amber",
                            IsDeleted = false,
                            LastName = "Midthunder"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "George",
                            IsDeleted = false,
                            LastName = "Clooney"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Y'Lan",
                            IsDeleted = false,
                            LastName = "Noel"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Bradley",
                            IsDeleted = false,
                            LastName = "Cooper"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Chloë ",
                            IsDeleted = false,
                            LastName = "Moretz"
                        });
                });

            modelBuilder.Entity("MovieForum.Data.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuthorId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisLikesCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int");

                    b.Property<int?>("MovieId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("PostedOn")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("MovieId");

                    b.ToTable("Comments");

                    b.HasCheckConstraint("CK_Comments_Content", "(LEN(Content)) >= 10");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Content = "This movie is awful!",
                            DisLikesCount = 0,
                            IsDeleted = false,
                            LikesCount = 0,
                            MovieId = 1,
                            PostedOn = new DateTime(2022, 11, 4, 22, 2, 53, 146, DateTimeKind.Local).AddTicks(8690)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Content = "Amazing movie! I strongly recomend it!",
                            DisLikesCount = 0,
                            IsDeleted = false,
                            LikesCount = 0,
                            MovieId = 2,
                            PostedOn = new DateTime(2022, 11, 4, 22, 2, 53, 151, DateTimeKind.Local).AddTicks(1885)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Content = "It's not as good as the first and repeats the first film's plot but 2 Fast 2 Furious is still fun due to great performances from Paul Walker and Tyrese Gibson and their great chemistry. The enjoyable and over the top action helps as well.!",
                            DisLikesCount = 0,
                            IsDeleted = false,
                            LikesCount = 0,
                            MovieId = 3,
                            PostedOn = new DateTime(2022, 11, 4, 22, 2, 53, 151, DateTimeKind.Local).AddTicks(1945)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            Content = "The concept of the movie was good, but needed to be taken a bit further in my opinion with detail. A lot happens in the movie that basically requires the audience to accept without question.\r\n",
                            DisLikesCount = 0,
                            IsDeleted = false,
                            LikesCount = 0,
                            MovieId = 4,
                            PostedOn = new DateTime(2022, 11, 4, 22, 2, 53, 151, DateTimeKind.Local).AddTicks(1953)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            Content = "One of the greatest mindblowing movies of all the times!",
                            DisLikesCount = 0,
                            IsDeleted = false,
                            LikesCount = 0,
                            MovieId = 5,
                            PostedOn = new DateTime(2022, 11, 4, 22, 2, 53, 151, DateTimeKind.Local).AddTicks(1958)
                        });
                });

            modelBuilder.Entity("MovieForum.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 13,
                            IsDeleted = false,
                            Name = "Superhero"
                        });
                });

            modelBuilder.Entity("MovieForum.Data.Models.MovieActor", b =>
                {
                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("ActorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            ActorId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 6,
                            IsDeleted = false
                        },
                        new
                        {
                            MovieId = 7,
                            ActorId = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 8,
                            IsDeleted = false
                        },
                        new
                        {
                            MovieId = 9,
                            ActorId = 9,
                            IsDeleted = false
                        },
                        new
                        {
                            MovieId = 10,
                            ActorId = 10,
                            IsDeleted = false
                        },
                        new
                        {
                            MovieId = 11,
                            ActorId = 11,
                            IsDeleted = false
                        },
                        new
                        {
                            MovieId = 12,
                            ActorId = 12,
                            IsDeleted = false
                        },
                        new
                        {
                            MovieId = 13,
                            ActorId = 13,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("MovieForum.Data.Models.MovieTags", b =>
                {
                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("TagId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("MovieId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MoviesTags");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            TagId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            MovieId = 2,
                            TagId = 1,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("MovieForum.Data.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Rating");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            MovieId = 2,
                            Rate = 5,
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            MovieId = 2,
                            Rate = 7,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("MovieForum.Data.Models.Reaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disliked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Liked")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.ToTable("LikesDislikes");
                });

            modelBuilder.Entity("MovieForum.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("MovieForum.Data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasCheckConstraint("CK_Tags_TagName", "(LEN(TagName))>= 2");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            TagName = "drama"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            TagName = "action"
                        });
                });

            modelBuilder.Entity("MovieForum.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasCheckConstraint("CK_Users_Username", "(LEN(Username))>= 4");

                    b.HasCheckConstraint("CK_Users_FirstName", "(LEN(FirstName))>= 4");

                    b.HasCheckConstraint("CK_Users_LastName", "(LEN(LastName))>= 4");

                    b.HasCheckConstraint("CK_Users_Password", "(LEN(Password))>= 8");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "fakeemail@gmail.com",
                            FirstName = "Angel",
                            ImagePath = "gum.jpg",
                            IsBlocked = false,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            LastName = "Marinski",
                            Password = "AQAAAAEAACcQAAAAEAysoiTt6oB1u4poBwj3Ax8GBSj9ZQzyJj2hDQ2v5K/DuLK/scCqW80vyXBB61Tl+w==",
                            RoleId = 2,
                            Username = "AngelMarinski"
                        },
                        new
                        {
                            Id = 2,
                            Email = "adminsemail@gmail.com",
                            FirstName = "Maggie",
                            ImagePath = "anais.png",
                            IsBlocked = false,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            LastName = "TheBoss",
                            Password = "AQAAAAEAACcQAAAAEPe5LQ/M4j5EwJfAxTZiPZq1GTT6xjVJV9O/j3vGYm3IWkB03E8YDw4z0L1/soi8yA==",
                            RoleId = 1,
                            Username = "Maggie"
                        },
                        new
                        {
                            Id = 3,
                            Email = "morefakeemails@gmail.com",
                            FirstName = "Radoslav",
                            ImagePath = "darw.png",
                            IsBlocked = false,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            LastName = "Berov",
                            Password = "AQAAAAEAACcQAAAAEHzy3sxwos7yJN+Mp1pyUL2Te7s0jE/40L7x+05rA2aXJ+zYHLIbM/P6fJnYoc5GNg==",
                            RoleId = 1,
                            Username = "Rado561"
                        },
                        new
                        {
                            Id = 4,
                            Email = "agent007@gmail.com",
                            FirstName = "James",
                            ImagePath = "bond.png",
                            IsBlocked = false,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            LastName = "Bond",
                            Password = "AQAAAAEAACcQAAAAEHcwFfNE7Y5Cf1wf4L1NnAxQk28ZLfIcvW3HsVdC07q6GBKKrp9w6vvRUi6dGARw+Q==",
                            RoleId = 1,
                            Username = "James96"
                        },
                        new
                        {
                            Id = 5,
                            Email = "mzfb@gmail.com",
                            FirstName = "Mark",
                            ImagePath = "marck.jpg",
                            IsBlocked = false,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            LastName = "zuckerberg",
                            Password = "AQAAAAEAACcQAAAAEMttkl2cnjR+GdBeEa85P49c7bd3x0ViDpjJlj8z6TboXM6GXnON0MVXEWwHvGHHpw==",
                            RoleId = 1,
                            Username = "MarkZ"
                        });
                });

            modelBuilder.Entity("MovieForum.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuthorID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Posted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorID");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasCheckConstraint("CK_Movies_Title", "(LEN(Title))>= 2");

                    b.HasCheckConstraint("CK_Movies_Content", "(LEN(Content))>= 32");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorID = 1,
                            Content = "After more than thirty years of service, military awards, medals and decorations for extraordinary heroism in combat, distinguished US Navy Captain Pete Mitchell, call sign Maverick, finds himself exactly where he belongs: pushing the limits as a top test pilot. Having spent years avoiding promotions after the events of Top Gun (1986), Maverick must now confront the ugly past and an uncertain future while tasked with training the next generation of elite fighter pilots for a nearly impossible suicide mission. But as the veteran naval aviator prepares the brilliant graduates for the top-secret assignment, stretching the rules to the breaking point, Mitchell has to face an equally critical challenge: navigate through an uncomfortable, bitter relationship with a hotshot lieutenant holding a grudge. Can Maverick and his Top Guns perform a miracle, give the enemy hell, and come back home in one piece?",
                            GenreId = 5,
                            ImagePath = "Images/top-gun.jpg",
                            IsDeleted = false,
                            Posted = new DateTime(2022, 11, 4, 22, 2, 53, 151, DateTimeKind.Local).AddTicks(6679),
                            ReleaseDate = new DateTime(2022, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Top Gun:Maverick"
                        },
                        new
                        {
                            Id = 2,
                            AuthorID = 2,
                            Content = "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.\r\n\r\nPeter Parker's secret identity is revealed to the entire world. Desperate for help, Peter turns to Doctor Strange to make the world forget that he is Spider-Man. The spell goes horribly wrong and shatters the multiverse, bringing in monstrous villains that could destroy the world.\r\n\r\nPicking up where Far From Home left off, Peter Parker's whole world is turned upside down when his old enemy Mysterio posthumously reveals his identity to the public. Wanting to make his identity a secret, Peter turns to Doctor Strange for help. But when Strange's spell goes haywire, Peter must go up against five deadly new enemies--the Green Goblin, Dr. Octopus, Electro, the Lizard and Sandman--all while discovering what it truly means to be Spider-Man.",
                            GenreId = 13,
                            ImagePath = "Images/spider-man.jpg",
                            IsDeleted = false,
                            Posted = new DateTime(2022, 11, 4, 22, 2, 53, 151, DateTimeKind.Local).AddTicks(7117),
                            ReleaseDate = new DateTime(2021, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spiderman: No Way Home"
                        },
                        new
                        {
                            Id = 3,
                            AuthorID = 3,
                            Content = "Former cop Brian O'Conner is called upon to bust a dangerous criminal and he recruits the help of a former childhood friend and street racer who has a chance to redeem himself.",
                            GenreId = 4,
                            ImagePath = "Images/2f2f.jpg",
                            IsDeleted = false,
                            Posted = new DateTime(2022, 11, 4, 22, 2, 53, 151, DateTimeKind.Local).AddTicks(7141),
                            ReleaseDate = new DateTime(2003, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "2 Fast 2 Furious"
                        },
                        new
                        {
                            Id = 4,
                            AuthorID = 4,
                            Content = "A 1950s housewife living with her husband in a utopian experimental community begins to worry that his glamorous company could be hiding disturbing secrets.",
                            GenreId = 4,
                            ImagePath = "Images/dwd.jpg",
                            IsDeleted = false,
                            Posted = new DateTime(2022, 11, 4, 22, 2, 53, 151, DateTimeKind.Local).AddTicks(7148),
                            ReleaseDate = new DateTime(2022, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Don't Worry Darling"
                        },
                        new
                        {
                            Id = 5,
                            AuthorID = 5,
                            Content = "For his final assignment, a top temporal agent must pursue the one criminal that has eluded him throughout time. The chase turns into a unique, surprising and mind-bending exploration of love, fate, identity and time travel taboos.\r\n\r\nPREDESTINATION chronicles the life of a Temporal Agent sent on an intricate series of time-travel journeys designed to ensure the continuation of his law enforcement career for all eternity. Now, on his final assignment, the Agent must pursue the one criminal that has eluded him throughout time.",
                            GenreId = 8,
                            ImagePath = "Images/predestination.jpg",
                            IsDeleted = false,
                            Posted = new DateTime(2022, 11, 4, 22, 2, 53, 151, DateTimeKind.Local).AddTicks(7154),
                            ReleaseDate = new DateTime(2014, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Predestination"
                        },
                        new
                        {
                            Id = 6,
                            AuthorID = 1,
                            Content = "Three friends discover a mysterious machine that takes pictures twenty-four hours into the future, and conspire to use it for personal gain, until disturbing and dangerous images begin to develop.\r\n\r\nThree friends discover a time machine which takes pictures of the future. They begin to use it to win race bets and everything goes fine till one gets greedier than another. They begin to lose faith in each other giving a sense of backstabbing as uglier truths unfold in the photos and the situation soon gets out of control.",
                            GenreId = 8,
                            ImagePath = "Images/timelapse.jpg",
                            IsDeleted = false,
                            Posted = new DateTime(2022, 11, 4, 22, 2, 53, 151, DateTimeKind.Local).AddTicks(7163),
                            ReleaseDate = new DateTime(2014, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Time Lapse"
                        },
                        new
                        {
                            Id = 7,
                            AuthorID = 2,
                            Content = "Foul-mouthed mutant mercenary Wade Wilson (a.k.a. Deadpool) assembles a team of fellow mutant rogues to protect a young boy with supernatural abilities from the brutal, time-traveling cyborg Cable.\r\n\r\nAfter losing Vanessa (Morena Baccarin), the love of his life, 4th-wall breaking mercenary Wade Wilson aka Deadpool (Ryan Reynolds) must assemble a team and protect a young, fat mutant Russell Collins aka Firefist (Julian Dennison) from Cable (Josh Brolin), a no-nonsense, dangerous cyborg from the future, and must also learn the most important lesson of all: to be part of a family again.",
                            GenreId = 11,
                            ImagePath = "Images/dp2.jpg",
                            IsDeleted = false,
                            Posted = new DateTime(2022, 11, 4, 22, 2, 53, 151, DateTimeKind.Local).AddTicks(7169),
                            ReleaseDate = new DateTime(2018, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Deadpool 2"
                        },
                        new
                        {
                            Id = 8,
                            AuthorID = 3,
                            Content = "Six people unwillingly find themselves locked in another series of escape rooms, slowly uncovering what they have in common to survive. Joining forces with two of the original survivors, they soon discover they've all played the game before.\r\n\r\nAfter escaping death by the skin of their teeth and surviving the bloody games devised by the nefarious Minos Corporation, lucky players Zoey and Ben are now coping with trauma after the events of Escape Room (2019). But instead of finding answers and closure, Zoey and Ben are soon dragged into another set of fiendishly designed death traps. And as a handful of former escapees join in, the competitors must work together to outsmart their inhuman tormentors and give their all to solve increasingly sophisticated puzzles. This time, the unseen perils are more elaborate, and escape is futile. Who shall live and who shall die in the sadistic Tournament of Champions?",
                            GenreId = 6,
                            ImagePath = "Images/escape-room.jpg",
                            IsDeleted = false,
                            Posted = new DateTime(2022, 11, 4, 22, 2, 53, 151, DateTimeKind.Local).AddTicks(7175),
                            ReleaseDate = new DateTime(2021, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Escape Room: Tournament of Champions"
                        },
                        new
                        {
                            Id = 9,
                            AuthorID = 3,
                            Content = "Naru, a skilled warrior of the Comanche Nation, fights to protect her tribe against one of the first highly-evolved Predators to land on Earth.",
                            GenreId = 3,
                            ImagePath = "Images/prey.png",
                            IsDeleted = false,
                            Posted = new DateTime(2022, 11, 4, 22, 2, 53, 151, DateTimeKind.Local).AddTicks(7180),
                            ReleaseDate = new DateTime(2022, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Prey"
                        },
                        new
                        {
                            Id = 10,
                            AuthorID = 4,
                            Content = "A divorced couple teams up and travels to Bali to stop their daughter from making the same mistake they think they made 25 years ago.",
                            GenreId = 4,
                            ImagePath = "Images/ticket.jpg",
                            IsDeleted = false,
                            Posted = new DateTime(2022, 11, 4, 22, 2, 53, 151, DateTimeKind.Local).AddTicks(7188),
                            ReleaseDate = new DateTime(2022, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ticket to Paradise"
                        },
                        new
                        {
                            Id = 11,
                            AuthorID = 5,
                            Content = "America's third political party, the New Founding Fathers of America, comes to power and conducts an experiment: no laws for 12 hours on Staten Island. No one has to stay on the island, but $5,000 is given to anyone who does.\r\n\r\nThis horror/action-adventure film from director Gerard McMurray serves as a prequel that recounts events that led up to the first Purge event. To push the crime rate below one percent for the rest of the year, the New Founding Fathers of America (NFFA) test a sociological theory that vents aggression for one night in one isolated community.",
                            GenreId = 9,
                            ImagePath = "Images/purge.jpg",
                            IsDeleted = false,
                            Posted = new DateTime(2022, 11, 4, 22, 2, 53, 151, DateTimeKind.Local).AddTicks(7193),
                            ReleaseDate = new DateTime(2018, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The First Purge"
                        },
                        new
                        {
                            Id = 12,
                            AuthorID = 3,
                            Content = "When one of their own is kidnapped by an angry gangster, the Wolf Pack must track down Mr. Chow, who has escaped from prison and is on the run.",
                            GenreId = 1,
                            ImagePath = "Images/hangover.jpg",
                            IsDeleted = false,
                            Posted = new DateTime(2022, 11, 4, 22, 2, 53, 151, DateTimeKind.Local).AddTicks(7343),
                            ReleaseDate = new DateTime(2013, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Hangover Part III"
                        },
                        new
                        {
                            Id = 13,
                            AuthorID = 1,
                            Content = "Set in the future when technology has subtly altered society, a woman discovers a secret connection to an alternate reality as well as a dark future of her own.",
                            GenreId = 2,
                            ImagePath = "Images/periph.jpg",
                            IsDeleted = false,
                            Posted = new DateTime(2022, 11, 4, 22, 2, 53, 151, DateTimeKind.Local).AddTicks(7351),
                            ReleaseDate = new DateTime(2022, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Peripheral"
                        });
                });

            modelBuilder.Entity("MovieForum.Data.Models.Comment", b =>
                {
                    b.HasOne("MovieForum.Data.Models.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MovieForum.Models.Movie", "Movie")
                        .WithMany("Comments")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieForum.Data.Models.MovieActor", b =>
                {
                    b.HasOne("MovieForum.Data.Models.Actor", "Actor")
                        .WithMany("Roles")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MovieForum.Models.Movie", "Movie")
                        .WithMany("Cast")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieForum.Data.Models.MovieTags", b =>
                {
                    b.HasOne("MovieForum.Models.Movie", "Movie")
                        .WithMany("Tags")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MovieForum.Data.Models.Tag", "Tag")
                        .WithMany("Movies")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MovieForum.Data.Models.Rating", b =>
                {
                    b.HasOne("MovieForum.Models.Movie", "Movie")
                        .WithMany("Rating")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieForum.Data.Models.Reaction", b =>
                {
                    b.HasOne("MovieForum.Data.Models.Comment", null)
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId");
                });

            modelBuilder.Entity("MovieForum.Data.Models.User", b =>
                {
                    b.HasOne("MovieForum.Data.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MovieForum.Models.Movie", b =>
                {
                    b.HasOne("MovieForum.Data.Models.User", "Author")
                        .WithMany("Movies")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieForum.Data.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MovieForum.Data.Models.Actor", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("MovieForum.Data.Models.Comment", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("MovieForum.Data.Models.Tag", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieForum.Data.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieForum.Models.Movie", b =>
                {
                    b.Navigation("Cast");

                    b.Navigation("Comments");

                    b.Navigation("Rating");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
